enes: "enes_2019"
id_1: "nocues"
id_2: "nhog"
max_caes_id: 10000
seed: 28

paths:
  data_raw: data/raw
  data_processed: data/processed
  data_graphs: data/graphs
  images: images

datasets:
  features:
    - name: "sex_id"
      type: "int"
      default: 0
    - name: "public_worker"
      type: "int"
      default: 0
    - name: "total_income"
      type: "float"
      default: NaN
    - name: "age"
      type: "int"
      default: NaN
    - name: "nivel_ed"
      type: "float"
      default: NaN

  enes_2019:
    source: data/raw/base_enespersonas.csv
    url: "https://datasets.datos.mincyt.gob.ar/dataset/b0c0ae96-4028-4d0e-919a-c6830110f6b6/resource/421a7e29-7d15-4b69-a2e8-d7242b58b770/download/base_enespersonas.csv"
    id_1: "nocues"
    id_2: "nhog"
    id_3: "miembro"
    id_caes: "v182caes"
    id_ciuo: "v183ciuo"
    id_cno: "v183cno"
    ponderation: null #"f_calib3"
    features:
      sex_id: "v109"
      public_worker: "v188" # en realidad es "v188"==1
      total_income: "ITI" # Ingreso total individual
      age: "v108"
      nivel_ed: "nivel_ed" # < 11

  enes_2021:
    source: data/raw/base_enespersonas_2021.csv
    url: null
    year: 2021
    id_1: "CUEST"
    id_2: null
    id_3: null
    id_caes: "CAES_num"
    id_ciuo: "CIUO_encuestado"
    id_cno: null
    ponderation: null
    features:
     sex_id: "SEXO"
     public_worker: "M3_7" # en realidad es "M3_7"==1
     total_income: null
     age: null
     nivel_ed: null

  eph_generic:
    source: data/raw/eph/*
    url: "https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/*"
    id_1: "CODUSU"
    id_2: "NRO_HOGAR"
    id_3: "COMPONENTE"
    id_caes: "PP04B_COD" # o "PP04B COD"
    id_ciuo: null
    id_cno: "PP04D_COD" # o "PP04D COD"
    ponderation: "PONDERA"
    features:
      sex_id: "PP03G_COD"
      public_worker: "CH04"
      total_income: "P47T" # Ingreso total individual
      age: "CH06"
      nivel_ed: "CH12" # < 10

caes:
  source: data/raw/nodelist_caes.csv
  id: "v182caes"
  label: "caeslabel"
  letra: "caesletra"
  grupo: "caesag"
  label_color: "caeslabel_color"
  letra_color: "caesletra_color"
  grupo_color: "caesag_color"
  partition: 1

ciuo:
  source: data/raw/nodelist_ciuo.csv
  id: "v183ciuo"
  label: "ciuolabel"
  letra: "ciuo1diglabel"
  grupo: "ciuo3cat"
  label_color: "ciuolabel_color"
  letra_color: "ciuo1diglabel_color"
  grupo_color: "ciuo3cat_color"
  partition: 0

cno:
  source: null
  id: "v183cno"
  label: null
  letra: null
  grupo: null
  label_color: null
  letra_color: null
  grupo_color: null
  partition: 0

figsizes:
  top_n_bar: [6, 4]
  edge_correlation: [6, 6]
  bipartite: [10, 8]
  projection: [8, 8]
  stacked: [12, 3.5]
  heatmap: [16, 10]
  histogram: [8, 6]
  catplot: [10, 5]

# Colormaps for continuous-feature projection plots.
cmaps:
  female_pct: "coolwarm"
  public_sector_pct: "PRGn"
  default: "magma"

community:
  resolution:
    caes: ["0.9"]
    ciuo: ["1.9"]
    cno: ["1.0"]
