enes: "enes_2019"
id_1: "nocues"
id_2: "nhog"
id_caes: "v182caes"
id_ciuo: "v183ciuo"
max_caes_id: 10000
logscale: false

paths:
  data_raw: data/raw
  data_processed: data/processed
  images: images

datasets:
  features:
    - name: "sex_id"
      type: "int"
      default: 0
    - name: "public_worker"
      type: "int"
      default: 0
    - name: "total_income"
      type: "float"
      default: NaN

  enes_2019:
    source: null
    url: "https://datasets.datos.mincyt.gob.ar/dataset/b0c0ae96-4028-4d0e-919a-c6830110f6b6/resource/421a7e29-7d15-4b69-a2e8-d7242b58b770/download/base_enespersonas.csv"
    id_1: "nocues"
    id_2: "nhog"
    id_caes: "v182caes"
    id_ciuo: "v183ciuo"
    features:
      sex_id: "v109"
      public_worker: "v188" # en realidad es "v188"==1
      total_income: "ITI"

  enes_2021:
    source: data/raw/base_enespersonas_2021.csv
    url: null
    year: 2021
    id_1: "CUEST"
    id_2: null
    id_caes: "CAES_num"
    id_ciuo: "CIUO_encuestado"
    features:
     sex_id: "SEXO"
     public_worker: "M3_7" # en realidad es "M3_7"==1
     total_income: null

caes:
  source: data/raw/nodelist_caes.csv
  id: "v182caes"
  label: "caeslabel"
  letra: "caesletra"
  grupo: "caesag"
  label_color: "caeslabel_color"
  letra_color: "caesletra_color"
  grupo_color: "caesag_color"
  partition: 1

ciuo:
  source: data/raw/nodelist_ciuo.csv
  id: "v183ciuo"
  label: "ciuolabel"
  letra: "ciuo1diglabel"
  grupo: "ciuo3cat"
  label_color: "ciuolabel_color"
  letra_color: "ciuo1diglabel_color"
  grupo_color: "ciuo3cat_color"
  partition: 0

colors:
  community_palette:
    - "C0"
    - "C1"
    - "C2"
    - "C3"
    - "C4"
    - "C5"
    - "C6"
    - "C7"
    - "C8"
    - "C9"
    - "gold"
    - "darkred"
    - "navy"
    - "darkcyan"

figsizes:
  top_n_bar: [6, 4]
  edge_correlation: [6, 6]
  bipartite: [20, 6]
  projection: [8, 8]
  stacked: [12, 3.5]

plot_font_size: 14
